nodeLinker: pnp

npmAuthToken: "${NPM_AUTH_TOKEN-notoken}"

npmPublishAccess: public

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

pnpMode: loose

yarnPath: .yarn/releases/yarn-3.2.0.cjs
