name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.target_commitish }}

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install

      - name: Set up git
        run: |
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git config --local user.name 'github-actions[bot]'

      - name: Bump version to ${{ github.event.release.tag_name }}
        run: |
          yarn workspace @ensdomains/ensjs version:create ${{ github.event.release.tag_name }}
          git add .
          git commit -m "${{ github.event.release.tag_name }}"

      - name: Publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn workspace @ensdomains/ensjs npm publish

      - name: Push changes
        run: git push
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
